### ISSUE TITLE
Platform -Backend Installation error

### ISSUE THREAD

**Issue by syaikhipin** [chainjet/platform#1]
I got some error while running yarn start:dev scheduler

It keeps error like this [Nest] ERROR [BlockchainListenerService] Blockchain integration not found

**Comment by marian2js** [comment]
Hi there! Have you populated the integrations? You need to run `yarn start bootstrap`

**Comment by syaikhipin** [comment]
Dear @marian2js , i have run yarn start bootstrap previously, and got error too

**Comment by marian2js** [comment]
@syaikhipin I just ran a clean install, but I didn't run on this issue. Have you added the MongoDB URL on the .env file? If so, could you check if the integrations collection has any items on it?

**Comment by syaikhipin** [comment]
@marian2js already did, but I catch error like this : Error: connect ETIMEDOUT 185.199.111.133:443
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
error Command failed with exit code 1.
When i try to run yarn start bootstrap

**Comment by marian2js** [comment]
@syaikhipin The error means that the connection with MongoDB is failing.
The `MONGO_URI` env variable should be a MongoDB [connection string](https://www.mongodb.com/docs/manual/reference/connection-string/).

It should look like `MONGO_URI=mongodb://185.199.111.133:443/chainjet`. You can find more examples [here](https://www.mongodb.com/docs/manual/reference/connection-string/#examples-1).
